# Generated by Django 4.2.5 on 2023-10-31 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=5)),
                ('apellido', models.CharField(max_length=5)),
                ('email', models.EmailField(max_length=16)),
                ('mensaje', models.CharField(max_length=350)),
            ],
        ),
    ]
