# Generated by Django 4.2.5 on 2023-11-14 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='mensaje',
            field=models.TextField(max_length=350),
        ),
    ]
