# Generated by Django 4.2.5 on 2023-11-20 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='body',
            new_name='mensaje',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='name',
            new_name='nombre',
        ),
    ]
